# This pyproject.toml installs repo-wide dev dependencies
[project]
name = "foxglove-sdk-monorepo"
version = "0.0.0"
requires-python = ">=3.9"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
black = "^25.1.0"
