[package]
name = "example-mcap"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
foxglove = { path = "../../foxglove" }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4.5"
env_logger = "0.11.5"
mcap = "0.14.1"
schemars = "0.8.21"
serde = { version = "1.0", features = ["derive"] }
